name: Deploy

on:
  push:
    branches:
      - master
      - main
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: deploy
      run: make deploy
